/**
 * Domain Error Codes
 * Centralized error codes for consistent API responses
 */

export enum ErrorCode {
  // Validation Errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',

  // Authentication Errors
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_REVOKED = 'TOKEN_REVOKED',

  // Authorization Errors
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Resource Errors
  NOT_FOUND = 'NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // State Transition Errors
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  INVALID_STATUS = 'INVALID_STATUS',

  // Quotation Errors
  QUOTATION_NOT_ACCEPTED = 'QUOTATION_NOT_ACCEPTED',
  QUOTATION_ALREADY_CONVERTED = 'QUOTATION_ALREADY_CONVERTED',
  QUOTATION_EXPIRED = 'QUOTATION_EXPIRED',

  // Sales Order Errors
  ORDER_NOT_CONFIRMABLE = 'ORDER_NOT_CONFIRMABLE',
  ORDER_ALREADY_DISPATCHED = 'ORDER_ALREADY_DISPATCHED',
  ORDER_ALREADY_CONFIRMED = 'ORDER_ALREADY_CONFIRMED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_PENDING = 'ORDER_PENDING',

  // Inventory Errors
  INSUFFICIENT_INVENTORY = 'INSUFFICIENT_INVENTORY',
  INVENTORY_NOT_FOUND = 'INVENTORY_NOT_FOUND',
  INVALID_QUANTITY = 'INVALID_QUANTITY',

  // Dispatch Errors
  DISPATCH_EXCEEDS_RESERVED = 'DISPATCH_EXCEEDS_RESERVED',
  DISPATCH_EXCEEDS_ORDER = 'DISPATCH_EXCEEDS_ORDER',
  DUPLICATE_DISPATCH = 'DUPLICATE_DISPATCH',

  // Concurrency Errors
  CONCURRENT_MODIFICATION = 'CONCURRENT_MODIFICATION',
  LOCK_ACQUISITION_FAILED = 'LOCK_ACQUISITION_FAILED',

  // Duplicate Resource
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',

  // Business Rule Violations
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',

  // Internal Errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
}
