import { useState } from 'react';
import { useCustomers, useCreateCustomer, useCustomerActivities, useCreateCustomerActivity, useCompleteCustomerActivity, useEnquiries, useQuotations, useSalesOrders } from '../api/hooks';
import type { CustomerActivityType } from '../api/types';
import { formatMoney } from '../lib/format';

const blank = { name: '', email: '', phone: '', contactPerson: '', address: '', city: '', state: '', pincode: '', gstNumber: '' };
const activityTypes: CustomerActivityType[] = ['CALL', 'EMAIL', 'MEETING', 'TASK', 'NOTE'];

export default function Customers() {
  const { data, isLoading } = useCustomers(1, 100); const enquiries = useEnquiries(1, 100); const quotations = useQuotations(1, 100); const orders = useSalesOrders(1, 100); const create = useCreateCustomer();
  const [open, setOpen] = useState(false); const [form, setForm] = useState(blank); const [selectedId, setSelectedId] = useState('');
  const [activityOpen, setActivityOpen] = useState(false); const [activity, setActivity] = useState({ type: 'CALL' as CustomerActivityType, subject: '', notes: '', dueAt: '' });
  const activities = useCustomerActivities(selectedId); const createActivity = useCreateCustomerActivity(); const completeActivity = useCompleteCustomerActivity();
  const customerEnquiries = enquiries.data?.items.filter((item) => item.customerId === selectedId) ?? [];
  const customerQuotations = quotations.data?.items.filter((item) => item.customerId === selectedId) ?? [];
  const customerOrders = orders.data?.items.filter((item) => item.customerId === selectedId) ?? [];
  const lifecycle = customerOrders.length ? 'Order' : customerQuotations.length ? 'Quotation' : customerEnquiries.length ? 'Enquiry' : 'Prospect';
  const customerQuoteValue = customerQuotations.reduce((sum, quotation) => sum + Number(quotation.grandTotal), 0);
  const customerDiscounts = customerQuotations.reduce((sum, quotation) => sum + Number(quotation.totalDiscount), 0);
  const set = (key: keyof typeof blank, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); create.mutate(form, { onSuccess: () => { setForm(blank); setOpen(false); } }); };
  const submitActivity = (event: React.FormEvent) => { event.preventDefault(); createActivity.mutate({ customerId: selectedId, ...activity, dueAt: activity.dueAt ? new Date(activity.dueAt).toISOString() : undefined }, { onSuccess: () => { setActivityOpen(false); setActivity({ type: 'CALL', subject: '', notes: '', dueAt: '' }); } }); };
  if (isLoading) return <div className="animate-pulse text-slate-400">Loading customers...</div>;
  return <div className="space-y-5">
    <header className="flex items-center justify-between"><div><h2 className="text-2xl font-bold text-slate-100">Customer 360</h2><p className="text-sm text-slate-400">Master data, follow-ups, and the complete customer relationship timeline.</p></div><button onClick={() => setOpen(true)} className="rounded-md bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950">Add customer</button></header>
    <div className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="overflow-x-auto rounded-lg border border-slate-800 bg-slate-900"><table className="min-w-full divide-y divide-slate-800"><thead className="bg-slate-950"><tr>{['Name', 'Contact', 'Phone', 'City', 'GST number'].map((heading) => <th key={heading} className="px-5 py-3 text-left text-xs font-medium uppercase text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-800">{data?.items.map((customer) => <tr key={customer.id} onClick={() => setSelectedId(customer.id)} className={`cursor-pointer ${selectedId === customer.id ? 'bg-cyan-400/10' : 'hover:bg-slate-800/50'}`}><td className="px-5 py-4 text-sm font-medium text-slate-100">{customer.name}</td><td className="px-5 py-4 text-sm text-slate-400">{customer.contactPerson || customer.email || '-'}</td><td className="px-5 py-4 text-sm text-slate-400">{customer.phone || '-'}</td><td className="px-5 py-4 text-sm text-slate-400">{customer.city || '-'}</td><td className="px-5 py-4 text-sm text-slate-400">{customer.gstNumber || '-'}</td></tr>)}</tbody></table></div>
      <aside className="rounded-lg border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-slate-100">Customer flow</h3><p className="text-xs text-slate-500">{selectedId ? `Current stage: ${lifecycle}` : 'Select a customer to view activity'}</p></div>{selectedId && <button onClick={() => setActivityOpen(true)} className="rounded-md border border-cyan-500 px-3 py-1.5 text-xs text-cyan-300">Add follow-up</button>}</div>{selectedId && <><div className="mt-4 grid grid-cols-4 gap-1 text-center text-[10px] uppercase text-slate-500">{['Prospect', 'Enquiry', 'Quotation', 'Order'].map((stage) => <div key={stage} className={`border-t-2 pt-2 ${['Prospect', 'Enquiry', 'Quotation', 'Order'].indexOf(stage) <= ['Prospect', 'Enquiry', 'Quotation', 'Order'].indexOf(lifecycle) ? 'border-cyan-400 text-cyan-300' : 'border-slate-700'}`}>{stage}</div>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-lg bg-slate-950/60 p-3"><p className="text-[10px] uppercase text-slate-500">Quoted value</p><p className="mt-1 text-sm font-semibold text-slate-100">{formatMoney(customerQuoteValue)}</p></div><div className="rounded-lg bg-orange-50 p-3"><p className="text-[10px] uppercase text-orange-700">Discount granted</p><p className="mt-1 text-sm font-semibold text-orange-800">{formatMoney(customerDiscounts)}</p></div></div><div className="mt-5 space-y-3">{activities.data?.map((item) => <div key={item.id} className={`border-l-2 pl-3 ${item.completedAt ? 'border-emerald-500 opacity-60' : 'border-cyan-500'}`}><div className="flex justify-between gap-2"><p className="text-sm font-medium text-slate-200">{item.subject}</p><span className="text-[10px] uppercase text-slate-500">{item.type}</span></div><p className="mt-1 text-xs text-slate-400">{item.notes || 'No notes'}{item.dueAt && ` • Due ${new Date(item.dueAt).toLocaleDateString()}`}</p>{!item.completedAt && <button onClick={() => completeActivity.mutate({ customerId: selectedId, activityId: item.id })} className="mt-2 text-xs text-emerald-400">Mark complete</button>}</div>)}{!activities.data?.length && <p className="text-sm text-slate-500">No follow-ups recorded.</p>}</div></>}</aside></div>
    {open && <div className="fixed inset-0 z-20 flex items-center justify-center bg-slate-950/80 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-lg border border-slate-700 bg-slate-900 p-6"><h3 className="mb-5 text-lg font-semibold text-slate-100">New customer</h3><div className="grid gap-4 sm:grid-cols-2">{Object.keys(blank).map((key) => <label key={key} className="text-sm text-slate-300">{key.replace(/[A-Z]/g, (letter) => ` ${letter}`).replace(/^./, (letter) => letter.toUpperCase())}<input required={key === 'name'} value={form[key as keyof typeof blank]} onChange={(event) => set(key as keyof typeof blank, event.target.value)} className="mt-1 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" /></label>)}</div><button disabled={create.isPending} className="mt-6 rounded-md bg-cyan-500 px-4 py-2 font-semibold text-slate-950">Create customer</button></form></div>}
    {activityOpen && <div className="fixed inset-0 z-20 flex items-center justify-center bg-slate-950/80 p-4"><form onSubmit={submitActivity} className="w-full max-w-lg rounded-lg border border-slate-700 bg-slate-900 p-6"><h3 className="mb-5 text-lg font-semibold text-slate-100">Schedule customer follow-up</h3><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-300">Type<select value={activity.type} onChange={(e) => setActivity({ ...activity, type: e.target.value as CustomerActivityType })} className="mt-1 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100">{activityTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-sm text-slate-300">Due date<input type="datetime-local" value={activity.dueAt} onChange={(e) => setActivity({ ...activity, dueAt: e.target.value })} className="mt-1 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" /></label></div><input required placeholder="Subject" value={activity.subject} onChange={(e) => setActivity({ ...activity, subject: e.target.value })} className="mt-4 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" /><textarea placeholder="Notes" value={activity.notes} onChange={(e) => setActivity({ ...activity, notes: e.target.value })} className="mt-4 h-24 w-full rounded-md border border-slate-700 bg-slate-950 p-3 text-slate-100" /><div className="mt-5 flex gap-3"><button type="button" onClick={() => setActivityOpen(false)} className="rounded-md border border-slate-700 px-4 py-2 text-slate-300">Cancel</button><button className="rounded-md bg-cyan-500 px-4 py-2 font-semibold text-slate-950">Schedule follow-up</button></div></form></div>}
  </div>;
}
